***importing libraries***

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


***importing dataset***

In [30]:
df= pd.read_csv('/content/breast_cancer.csv')
df

Sample code number  Clump Thickness  ...  Mitoses  Class
0               1000025                5  ...        1      2
1               1002945                5  ...        1      2
2               1015425                3  ...        1      2
3               1016277                6  ...        1      2
4               1017023                4  ...        1      2
..                  ...              ...  ...      ...    ...
678              776715                3  ...        1      2
679              841769                2  ...        1      2
680              888820                5  ...        2      4
681              897471                4  ...        1      4
682              897471                4  ...        1      4

[683 rows x 11 columns]

In [31]:
x= df.iloc[:,1:-1].values
y= df.iloc[:,-1].values

In [32]:
print(x)

[[ 5  1  1 ...  3  1  1]
 [ 5  4  4 ...  3  2  1]
 [ 3  1  1 ...  3  1  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]


In [33]:
print(y)

[2 2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 2 4 2 2 2 2 2 2 4 2 2 2 4 2
 4 4 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4 2
 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4 4
 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 4 2 4
 4 2 2 4 2 2 4 4 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2 4 4 4 2 4
 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4 4 4 2 4 4
 2 4 4 4 2 4 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 4 2 4 4 4 2 2 2 2 4 4 4 4 4 2 4
 4 4 2 4 2 4 4 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2
 4 2 2 2 4 2 2 4 4 2 2 4 2 4 2 2 4 2 4 4 4 2 2 4 4 2 4 2 2 4 4 2 2 2 4 2 2
 2 4 4 2 2 2 4 2 2 4 4 4 4 4 4 2 2 2 2 4 4 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2
 2 2 4 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 2 2 4 2 4 2 4 2 2 2 2 4
 2 2 2 4 2 4 2 2 2 2 2 2 2 4 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 4 2 4 4 4 2
 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2 2 4 4 2 2 2 4 4 4 2 4 2 4 2 2
 2 2 2 2 2 2 2 2 2 2 4 2 

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [35]:
df.describe( )

Sample code number  Clump Thickness  ...     Mitoses       Class
count        6.830000e+02       683.000000  ...  683.000000  683.000000
mean         1.076720e+06         4.442167  ...    1.603221    2.699854
std          6.206440e+05         2.820761  ...    1.732674    0.954592
min          6.337500e+04         1.000000  ...    1.000000    2.000000
25%          8.776170e+05         2.000000  ...    1.000000    2.000000
50%          1.171795e+06         4.000000  ...    1.000000    2.000000
75%          1.238705e+06         6.000000  ...    1.000000    4.000000
max          1.345435e+07        10.000000  ...   10.000000    4.000000

[8 rows x 11 columns]

***splitting the dataset into the trainning set and test set***

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size= 0.2, random_state= 0)

***trainning the logistic regression model on the trainning set***

In [37]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

***predicting the test set result***

In [38]:
y_pred= classifier.predict(x_test)                        

***Making the confusion matrix***

In [39]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print(cm)

[[84  3]
 [ 3 47]]


we have 84+47 = 131 out of 137  prediction correct 

6 incorrect prediction

2 for benign, 4 for malignant-output // check in dataset

we can find accuracy like this also below:

In [40]:
(84+47)/(84+47+3+3)

0.9562043795620438

In [41]:
100*(84+47)/(84+47+3+3)

95.62043795620438

***computing the accuracy with K-fold cross validation***

In [49]:
from sklearn.model_selection import cross_val_score
accuracies= cross_val_score(estimator=classifier, X= x_train, y= y_train,cv=10)
print("Accuracy: ",format(accuracies.mean()*100))
print("Standard Deviation:",format(accuracies.std()*100))

Accuracy:  96.70033670033669
Standard Deviation: 1.9697976894447813
